name: Firrst_flow

on:
  push:
    branches: 
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "A demo build"
 
