name: Firrst_flow

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "A demo build"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: test phase
      run: echo "running"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy the app
        run: echo "deploying the app"
        
