name: Firrst_flow

on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: 
          echo "THis is first line"
          echo "THis is second line"
          echo "THis is third line"
          echo "THis is fourth line"
